version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  
    commands:
      - echo Installing dependencies
      - npm install
  pre_build:
    commands:
      - echo Fetching environment variables from SSM Parameter Store...
      - VITE_API_BASE_URL=$(aws ssm get-parameter --name "/todo-app/$ENVIRONMENT/VITE_API_BASE_URL" --region $AWS_DEFAULT_REGION --query "Parameter.Value" --output text)
  build:
    commands:
      - echo Prepare build
      - npm run build
  post_build:
    commands:
      - echo Post Build Actions

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: no
